// Code generated by protoc-gen-go. DO NOT EDIT.
// source: surface.proto

package surface_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldKind int32

const (
	FieldKind_SCALAR    FieldKind = 0
	FieldKind_MAP       FieldKind = 1
	FieldKind_ARRAY     FieldKind = 2
	FieldKind_REFERENCE FieldKind = 3
	FieldKind_ANY       FieldKind = 4
)

var FieldKind_name = map[int32]string{
	0: "SCALAR",
	1: "MAP",
	2: "ARRAY",
	3: "REFERENCE",
	4: "ANY",
}

var FieldKind_value = map[string]int32{
	"SCALAR":    0,
	"MAP":       1,
	"ARRAY":     2,
	"REFERENCE": 3,
	"ANY":       4,
}

func (x FieldKind) String() string {
	return proto.EnumName(FieldKind_name, int32(x))
}

func (FieldKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{0}
}

type TypeKind int32

const (
	TypeKind_STRUCT TypeKind = 0
	TypeKind_OBJECT TypeKind = 1
)

var TypeKind_name = map[int32]string{
	0: "STRUCT",
	1: "OBJECT",
}

var TypeKind_value = map[string]int32{
	"STRUCT": 0,
	"OBJECT": 1,
}

func (x TypeKind) String() string {
	return proto.EnumName(TypeKind_name, int32(x))
}

func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{1}
}

type Position int32

const (
	Position_BODY     Position = 0
	Position_HEADER   Position = 1
	Position_FORMDATA Position = 2
	Position_QUERY    Position = 3
	Position_PATH     Position = 4
	Position_SCHEMA   Position = 200
)

var Position_name = map[int32]string{
	0:   "BODY",
	1:   "HEADER",
	2:   "FORMDATA",
	3:   "QUERY",
	4:   "PATH",
	200: "SCHEMA",
}

var Position_value = map[string]int32{
	"BODY":     0,
	"HEADER":   1,
	"FORMDATA": 2,
	"QUERY":    3,
	"PATH":     4,
	"SCHEMA":   200,
}

func (x Position) String() string {
	return proto.EnumName(Position_name, int32(x))
}

func (Position) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{2}
}

// Field is a field in a definition and can be associated with
// a position in a request structure.
type Field struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Kind                 FieldKind `protobuf:"varint,3,opt,name=kind,proto3,enum=surface.v1.FieldKind" json:"kind,omitempty"`
	Format               string    `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Position             Position  `protobuf:"varint,5,opt,name=position,proto3,enum=surface.v1.Position" json:"position,omitempty"`
	NativeType           string    `protobuf:"bytes,6,opt,name=nativeType,proto3" json:"nativeType,omitempty"`
	FieldName            string    `protobuf:"bytes,7,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	ParameterName        string    `protobuf:"bytes,8,opt,name=parameterName,proto3" json:"parameterName,omitempty"`
	Serialize            bool      `protobuf:"varint,9,opt,name=serialize,proto3" json:"serialize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{0}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Field) GetKind() FieldKind {
	if m != nil {
		return m.Kind
	}
	return FieldKind_SCALAR
}

func (m *Field) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Field) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position_BODY
}

func (m *Field) GetNativeType() string {
	if m != nil {
		return m.NativeType
	}
	return ""
}

func (m *Field) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Field) GetParameterName() string {
	if m != nil {
		return m.ParameterName
	}
	return ""
}

func (m *Field) GetSerialize() bool {
	if m != nil {
		return m.Serialize
	}
	return false
}

// Type typically corresponds to a definition, parameter, or response
// in an API and is represented by a type in generated code.
type Type struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 TypeKind `protobuf:"varint,2,opt,name=kind,proto3,enum=surface.v1.TypeKind" json:"kind,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContentType          string   `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	TypeName             string   `protobuf:"bytes,6,opt,name=typeName,proto3" json:"typeName,omitempty"`
	SchemaField          string   `protobuf:"bytes,200,opt,name=schemaField,proto3" json:"schemaField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{1}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetKind() TypeKind {
	if m != nil {
		return m.Kind
	}
	return TypeKind_STRUCT
}

func (m *Type) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Type) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Type) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Type) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Type) GetSchemaField() string {
	if m != nil {
		return m.SchemaField
	}
	return ""
}

// Method is an operation of an API and typically has associated client and server code.
type Method struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	HandlerName          string   `protobuf:"bytes,6,opt,name=handlerName,proto3" json:"handlerName,omitempty"`
	ProcessorName        string   `protobuf:"bytes,7,opt,name=processorName,proto3" json:"processorName,omitempty"`
	ClientName           string   `protobuf:"bytes,8,opt,name=clientName,proto3" json:"clientName,omitempty"`
	ParametersTypeName   string   `protobuf:"bytes,9,opt,name=parametersTypeName,proto3" json:"parametersTypeName,omitempty"`
	ResponsesTypeName    string   `protobuf:"bytes,10,opt,name=responsesTypeName,proto3" json:"responsesTypeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{2}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Method) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Method) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Method) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetHandlerName() string {
	if m != nil {
		return m.HandlerName
	}
	return ""
}

func (m *Method) GetProcessorName() string {
	if m != nil {
		return m.ProcessorName
	}
	return ""
}

func (m *Method) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *Method) GetParametersTypeName() string {
	if m != nil {
		return m.ParametersTypeName
	}
	return ""
}

func (m *Method) GetResponsesTypeName() string {
	if m != nil {
		return m.ResponsesTypeName
	}
	return ""
}

// Model represents an API for code generation.
type Model struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Types                []*Type   `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Methods              []*Method `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_3306d3fe7fd759d5, []int{3}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Model) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func init() {
	proto.RegisterEnum("surface.v1.FieldKind", FieldKind_name, FieldKind_value)
	proto.RegisterEnum("surface.v1.TypeKind", TypeKind_name, TypeKind_value)
	proto.RegisterEnum("surface.v1.Position", Position_name, Position_value)
	proto.RegisterType((*Field)(nil), "surface.v1.Field")
	proto.RegisterType((*Type)(nil), "surface.v1.Type")
	proto.RegisterType((*Method)(nil), "surface.v1.Method")
	proto.RegisterType((*Model)(nil), "surface.v1.Model")
}

func init() { proto.RegisterFile("surface.proto", fileDescriptor_3306d3fe7fd759d5) }

var fileDescriptor_3306d3fe7fd759d5 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xff, 0x52, 0x7b, 0xf2, 0xf5, 0xd3, 0x76, 0x04, 0xc8, 0x42, 0x08, 0x85, 0x08, 0xa1,
	0xb4, 0xaa, 0x22, 0x28, 0x4f, 0xe0, 0xa6, 0xae, 0x2a, 0x20, 0x6d, 0x58, 0xdc, 0x8b, 0x5c, 0x1a,
	0x7b, 0xab, 0x58, 0x24, 0xb6, 0xf1, 0x9a, 0x4a, 0xf0, 0x40, 0x3c, 0x4b, 0xaf, 0x78, 0x18, 0x9e,
	0x00, 0xed, 0xd8, 0x4e, 0xb6, 0x4d, 0xee, 0x76, 0xcf, 0x9c, 0x3d, 0xbb, 0xe7, 0xcc, 0xd8, 0x70,
	0x20, 0x7f, 0x54, 0xb7, 0x71, 0x22, 0xc6, 0x65, 0x55, 0xd4, 0x05, 0x42, 0xb7, 0xbd, 0x7b, 0x37,
	0xfc, 0x6d, 0x82, 0x73, 0x91, 0x89, 0x65, 0x8a, 0x08, 0x76, 0x1e, 0xaf, 0x84, 0x6f, 0x0c, 0x8c,
	0x91, 0xc7, 0x69, 0xad, 0xb0, 0xfa, 0x67, 0x29, 0x7c, 0xb3, 0xc1, 0xd4, 0x1a, 0x8f, 0xc0, 0xfe,
	0x96, 0xe5, 0xa9, 0x6f, 0x0d, 0x8c, 0xd1, 0xff, 0xa7, 0x4f, 0xc7, 0x1b, 0xb1, 0x31, 0x09, 0x7d,
	0xcc, 0xf2, 0x94, 0x13, 0x05, 0x9f, 0x41, 0xef, 0xb6, 0xa8, 0x56, 0x71, 0xed, 0xdb, 0x24, 0xd0,
	0xee, 0xf0, 0x2d, 0xb8, 0x65, 0x21, 0xb3, 0x3a, 0x2b, 0x72, 0xdf, 0x21, 0x99, 0x27, 0xba, 0xcc,
	0xac, 0xad, 0xf1, 0x35, 0x0b, 0x5f, 0x02, 0xe4, 0x71, 0x9d, 0xdd, 0x89, 0x48, 0x3d, 0xa7, 0x47,
	0x6a, 0x1a, 0x82, 0x2f, 0xc0, 0xbb, 0x55, 0x97, 0x5f, 0x29, 0x07, 0xfb, 0x54, 0xde, 0x00, 0xf8,
	0x1a, 0x0e, 0xca, 0xb8, 0x8a, 0x57, 0xa2, 0x16, 0x15, 0x31, 0x5c, 0x62, 0x3c, 0x04, 0x95, 0x86,
	0x14, 0x55, 0x16, 0x2f, 0xb3, 0x5f, 0xc2, 0xf7, 0x06, 0xc6, 0xc8, 0xe5, 0x1b, 0x60, 0xf8, 0xd7,
	0x00, 0x9b, 0xae, 0xda, 0x95, 0xd3, 0xa8, 0xcd, 0xc4, 0xdc, 0x36, 0xa3, 0xce, 0x68, 0x91, 0x0c,
	0xa0, 0x9f, 0x0a, 0x99, 0x54, 0x59, 0x49, 0xee, 0x2d, 0x12, 0xd1, 0x21, 0xc5, 0x48, 0x8a, 0xbc,
	0x16, 0x79, 0x4d, 0x5e, 0x9b, 0xe4, 0x74, 0x08, 0x8f, 0xa0, 0x47, 0xde, 0xa4, 0xef, 0x0c, 0xac,
	0x51, 0xff, 0xf4, 0x70, 0xab, 0x07, 0xbc, 0x25, 0xe0, 0x73, 0x70, 0x55, 0xd3, 0xc8, 0x74, 0x93,
	0xda, 0x7a, 0x8f, 0xaf, 0xa0, 0x2f, 0x93, 0x85, 0x58, 0xc5, 0x74, 0xc4, 0xbf, 0x6f, 0x0c, 0xe9,
	0xd8, 0xf0, 0x8f, 0x09, 0xbd, 0xa9, 0xa8, 0x17, 0x45, 0xaa, 0xd2, 0x29, 0x4a, 0x51, 0xc5, 0xf4,
	0xec, 0x86, 0xba, 0x01, 0x54, 0x28, 0x65, 0x5c, 0x2f, 0xba, 0x41, 0x51, 0x6b, 0xd5, 0xfd, 0x15,
	0x9d, 0x6d, 0x5d, 0xb6, 0xbb, 0xc7, 0x11, 0xd8, 0xdb, 0x11, 0x74, 0x11, 0x3b, 0x5a, 0xc4, 0x03,
	0xe8, 0x2f, 0xe2, 0x3c, 0x5d, 0xb6, 0x1d, 0x6c, 0xcc, 0xe8, 0x10, 0x75, 0xb9, 0x2a, 0x12, 0x21,
	0x65, 0x51, 0x69, 0x73, 0xf0, 0x10, 0x54, 0x93, 0x94, 0x2c, 0x33, 0x91, 0xd7, 0xda, 0x20, 0x68,
	0x08, 0x8e, 0x01, 0xd7, 0x63, 0x21, 0xa3, 0x2e, 0x3b, 0x8f, 0x78, 0x3b, 0x2a, 0x78, 0x02, 0x87,
	0x95, 0x90, 0x65, 0x91, 0x4b, 0xb1, 0xa1, 0x03, 0xd1, 0xb7, 0x0b, 0xc3, 0xef, 0xe0, 0x4c, 0x8b,
	0x54, 0x2c, 0x77, 0x4e, 0xd1, 0x1b, 0x70, 0x54, 0x73, 0xa4, 0x6f, 0x52, 0x5b, 0xd9, 0xe3, 0x31,
	0xe2, 0x4d, 0x19, 0x4f, 0x60, 0xbf, 0x89, 0x52, 0xfa, 0x16, 0x31, 0x51, 0x67, 0x36, 0xfd, 0xe2,
	0x1d, 0xe5, 0x78, 0x02, 0xde, 0xfa, 0xbb, 0x44, 0x80, 0xde, 0x97, 0x49, 0xf0, 0x29, 0xe0, 0x6c,
	0x0f, 0xf7, 0xc1, 0x9a, 0x06, 0x33, 0x66, 0xa0, 0x07, 0x4e, 0xc0, 0x79, 0x30, 0x67, 0x26, 0x1e,
	0x80, 0xc7, 0xc3, 0x8b, 0x90, 0x87, 0x57, 0x93, 0x90, 0x59, 0x8a, 0x12, 0x5c, 0xcd, 0x99, 0x7d,
	0x3c, 0x04, 0xb7, 0x1b, 0x64, 0xd2, 0x88, 0xf8, 0xcd, 0x24, 0x62, 0x7b, 0x6a, 0x7d, 0x7d, 0xf6,
	0x21, 0x9c, 0x44, 0xcc, 0x38, 0x9e, 0x81, 0xdb, 0x7d, 0xb9, 0xe8, 0x82, 0x7d, 0x76, 0x7d, 0x3e,
	0x6f, 0x18, 0x97, 0x61, 0x70, 0x1e, 0x72, 0x66, 0xe0, 0x7f, 0xe0, 0x5e, 0x5c, 0xf3, 0xe9, 0x79,
	0x10, 0x05, 0xcc, 0x54, 0xd7, 0x7e, 0xbe, 0x09, 0xf9, 0x9c, 0x59, 0x8a, 0x3e, 0x0b, 0xa2, 0x4b,
	0x66, 0x63, 0x5f, 0x3d, 0xf0, 0x32, 0x9c, 0x06, 0xec, 0xde, 0xf8, 0xda, 0xa3, 0xff, 0xd5, 0xfb,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x8f, 0xbe, 0x40, 0xc0, 0x04, 0x00, 0x00,
}
